name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
      developmentVersion:
        description: 'Next development version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Setup Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "${{ secrets.SETTINGS_XML }}" > ~/.m2/settings.xml
      - name: Verify settings.xml
        run: |
          if [ ! -f ~/.m2/settings.xml ]; then
            echo "settings.xml was not created"
            exit 1
          fi
      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Release with Maven
        run: |
          mvn -B -s ~/.m2/settings.xml release:prepare release:perform \
          -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
          -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }} \
          -DskipTests